### ISSUE TITLE
long boot time due to script locking up device

### ISSUE THREAD

**Issue by hippi-viking** [britannic/Adblock#1] opened 2017-12-06 10:57 UTC
Hello,

Thanks for all the great work! One thing I noticed is that since installing your script on an Edgerouter X it now takes roughly half an hour for the web and ssh interfaces to start. There are a line in the syslog every minute informing that both interfaces are not yet able to start due to a resource being locked (very likely due to the blacklist script populating its database) - I can look it up exactly if interested in a few weeks when I'll get to my Edgerouters some 2000km away.
Could this behaviour be changed (to allow the management interfaces go up and _then_ populate the database say 5 minutes later)?

Cheers,
Istvan

**Comment by britannic** [comment] 2017-12-07 01:29
Please post the router OS version, which version of Adblock and an excerpt from your log file showing the behavior. I am not able to reproduce the problem on any of my ERLite routers. Please use a console cable to check your router's boot messages and post the output.

**Comment by britannic** [comment] 2018-01-29 23:28
Please try the latest version and report back. Closing this issue for now.

**Closed as completed by britannic** 2018-01-29 23:28 UTC
Labels: Need more information

**Comment by hippi-viking** [comment] 2018-11-20 15:13
Sorry for the late answer I moved countries and started a new life since. The new version doesn't have the interface lock-up issue anymore.
